platform :ios, '12.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # config.build_settings['DEVELOPMENT_TEAM'] = '<TEAM_ID>'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      # or disable code signing - seems to also work...
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end